### ISSUE TITLE
Calculate amount ml of the brewed coffee.

### ISSUE THREAD

**Issue by metya** [wdrs/FutulaCoffeeScale#1]
For example,

I brew the standard pour-over with a 1:16 ratio with 16-gram coffee. 
So I need to pour ~ 250 ml water. 
After it's done, the amount of coffee in a server is not 250 ml.
I want to calculate this amount. Amount of brewed coffee.
I can do it by just weighing the server without a spent coffee grounds and a pour-over. 

We know the dose of the coffee already in the app. We need to know somehow the weight of a pour-over. 
Then calculate the remaining amount of brewed coffee in grams or ml.

**Comment by wdrs** [comment]
Done in commit 5d4c96a92c70c2d8057ead3e85ee2c7c4443272a
